import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Container from '@/components/container/Container'
import Summary from './summary'
import SidebarSocialMedia from '@/components/sidebar-social-media/SidebarSocialMedia'
import Header from '@/components/header/Header'
import EntrySection from '@/components/entry-section/EntrySection'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Gabriel Barbosa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Header />
          <EntrySection />
          <SidebarSocialMedia />
        </Container>
      </main>
    </>
  )
}
