import About from '../components/about/About'
import Container from '../components/container/Container'
import EntrySection from '../components/entry-section/EntrySection'
import Header from '../components/header/Header'
import SidebarSocialMedia from '../components/sidebar-social-media/SidebarSocialMedia'
import { Inter } from '@next/font/google'
import Head from 'next/head'
import Experience from '../components/experience/Experience'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Gabriel Barbosa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Header />
          <SidebarSocialMedia />
          <EntrySection />
          <About />
          <Experience />
        </Container>
      </main>
    </>
  )
}
